name: Build and push Docker image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            rajaramesh/myapp:latest
            rajaramesh/myapp:${{ github.sha }}

      - name: If tag pushed, also tag as version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull rajaramesh1416/repo:${{ github.sha }}
          docker tag rajaramesh1416/repo:${{ github.sha }} rajaramesh1416/repo:${{ github.ref_name }}
          docker push rajaramesh1416/repo:${{ github.ref_name }}
